### ISSUE TITLE
Share your editor config

### ISSUE THREAD

**Issue by MathRobin** [adrienjoly/js-test#31]
Hi Adrien,

You should share your editor config file, as this, dev is standardized

**Comment by adrienjoly** [comment]
How do you usually do this?
(I use VSCode)

**Comment by MathRobin** [comment]
You've found^^

**Comment by adrienjoly** [comment]
@MathRobin I used an extension for VSCode. Still curious of how you generate this file for your different projects, tho.

**Comment by MathRobin** [comment]
I don't know for all IDE, but on Jetbrains, you can export it natively.
